// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: proto/auth.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

/** --- Register/Login/OTP/Refresh  --- */
export interface RegisterRequest {
  username: string;
  password: string;
  email: string;
  realname: string;
  gameName: string;
}

export interface RegisterResponse {
  success: boolean;
  auth_id: number;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  sessionId: string;
}

export interface VerifyOtpRequest {
  sessionId: string;
  otp: string;
}

export interface VerifyOtpResponse {
  access_token: string;
  refresh_token: string;
  auth_id: number;
  role: string;
}

export interface LogoutRequest {
  refreshToken: string;
}

export interface LogoutResponse {
  success: boolean;
}

export interface RefreshRequest {
  refreshToken: string;
}

export interface RefreshResponse {
  access_token: string;
  refresh_token: string;
}

/** --- User methods --- */
export interface ChangePasswordRequest {
  sessionId: string;
  oldPassword: string;
  newPassword: string;
}

export interface ChangePasswordResponse {
  success: boolean;
}

export interface SystemChangePasswordRequest {
  sessionId: string;
  newPassword: string;
}

export interface SystemChangePasswordResponse {
  success: boolean;
}

export interface ResetPasswordRequest {
  username: string;
  otp: string;
  newPassword: string;
}

export interface ResetPasswordResponse {
  success: boolean;
}

export interface ChangeEmailRequest {
  sessionId: string;
  newEmail: string;
}

export interface ChangeEmailResponse {
  success: boolean;
}

/** --- Admin methods --- */
export interface ChangeRoleRequest {
  /** user target */
  username: string;
  newRole: string;
}

export interface ChangeRoleResponse {
  success: boolean;
}

export interface BanUserRequest {
  username: string;
}

export interface BanUserResponse {
  success: boolean;
  userId: number;
}

export interface UnbanUserRequest {
  username: string;
}

export interface UnbanUserResponse {
  success: boolean;
}

/** --- Request OTP reset password --- */
export interface RequestResetPasswordRequest {
  username: string;
}

export interface RequestResetPasswordResponse {
  success: boolean;
}

export interface ChangeRolePartnerRequest {
  username: string;
}

export interface ChangeRolePartnerResponse {
  success: boolean;
}

export interface GetEmailUserRequest {
  id: number;
}

export interface GetEmailUserResponse {
  email: string;
}

export interface GetEmailUserByUsernameRequest {
  username: string;
}

export interface GetEmailUserByUsernameResponse {
  email: string;
}

export interface GetProfileRequest {
  id: number;
}

export interface GetProfileReponse {
  role: string;
  biBan: boolean;
  avatarUrl: string;
  username: string;
}

export interface SendEmailToUserRequest {
  who: string;
  title: string;
  content: string;
}

export interface SendemailToUserResponse {
  success: boolean;
}

export interface ChangeAvatarRequest {
  userId: number;
  avatarUrl: string;
}

export interface ChangeAvatarResponse {
  success: boolean;
}

export interface GetRealnameAvatarRequest {
  userIds: number[];
}

export interface RealnameAvatarInfo {
  userId: number;
  realname: string;
  avatarUrl: string;
}

export interface GetRealnameAvatarResponse {
  realnameAvatarInfo: RealnameAvatarInfo[];
}

export interface GetAllUserRequest {
}

export interface UserTraVe {
  userId: number;
  realname: string;
  avatarUrl: string;
}

export interface GetAllUserResponse {
  userTraVe: UserTraVe[];
}

export interface LoginWithGoogleRequest {
  tokenFromGoogle: string;
}

export interface LoginWithGoogleResponse {
  access_token: string;
  refresh_token: string;
  auth_id: number;
  role: string;
  register: boolean;
}

export interface GetTokenVersionRequest {
  userId: number;
}

export interface GetTokenVersionResponse {
  tokenVersion: number;
}

export interface SetTokenVersionRequest {
  username: string;
}

export interface SetTokenVersionResponse {
  success: boolean;
}

export interface GetBanRequest {
  userId: number;
}

export interface GetBanResponse {
  success: boolean;
}

export const AUTH_PACKAGE_NAME = "auth";

/** ===== SERVICE DEFINITION ===== */

export interface AuthServiceClient {
  /** user actions */

  register(request: RegisterRequest, metadata?: Metadata): Observable<RegisterResponse>;

  login(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  verifyOtp(request: VerifyOtpRequest, metadata?: Metadata): Observable<VerifyOtpResponse>;

  logout(request: LogoutRequest, metadata?: Metadata): Observable<LogoutResponse>;

  refresh(request: RefreshRequest, metadata?: Metadata): Observable<RefreshResponse>;

  setTokenVersion(request: SetTokenVersionRequest, metadata?: Metadata): Observable<SetTokenVersionResponse>;

  getTokenVersion(request: GetTokenVersionRequest, metadata?: Metadata): Observable<GetTokenVersionResponse>;

  getBan(request: GetBanRequest, metadata?: Metadata): Observable<GetBanResponse>;

  changePassword(request: ChangePasswordRequest, metadata?: Metadata): Observable<ChangePasswordResponse>;

  resetPassword(request: ResetPasswordRequest, metadata?: Metadata): Observable<ResetPasswordResponse>;

  requestResetPassword(
    request: RequestResetPasswordRequest,
    metadata?: Metadata,
  ): Observable<RequestResetPasswordResponse>;

  changeEmail(request: ChangeEmailRequest, metadata?: Metadata): Observable<ChangeEmailResponse>;

  changeRolePartner(request: ChangeRolePartnerRequest, metadata?: Metadata): Observable<ChangeRolePartnerResponse>;

  getEmailUser(request: GetEmailUserRequest, metadata?: Metadata): Observable<GetEmailUserResponse>;

  getEmailUserByUsername(
    request: GetEmailUserByUsernameRequest,
    metadata?: Metadata,
  ): Observable<GetEmailUserByUsernameResponse>;

  getProfile(request: GetProfileRequest, metadata?: Metadata): Observable<GetProfileReponse>;

  changeAvatar(request: ChangeAvatarRequest, metadata?: Metadata): Observable<ChangeAvatarResponse>;

  getRealnameAvatar(request: GetRealnameAvatarRequest, metadata?: Metadata): Observable<GetRealnameAvatarResponse>;

  getAllUser(request: GetAllUserRequest, metadata?: Metadata): Observable<GetAllUserResponse>;

  /** admin actions */

  changeRole(request: ChangeRoleRequest, metadata?: Metadata): Observable<ChangeRoleResponse>;

  banUser(request: BanUserRequest, metadata?: Metadata): Observable<BanUserResponse>;

  unbanUser(request: UnbanUserRequest, metadata?: Metadata): Observable<UnbanUserResponse>;

  sendEmailToUser(request: SendEmailToUserRequest, metadata?: Metadata): Observable<SendemailToUserResponse>;

  /** admin service gọi khi check account có đủ điều kiện đăng bán không */

  checkAccount(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  /** Login google */

  loginWithGoogle(request: LoginWithGoogleRequest, metadata?: Metadata): Observable<LoginWithGoogleResponse>;

  /** System (api cho hệ thống) */

  systemChangePassword(
    request: SystemChangePasswordRequest,
    metadata?: Metadata,
  ): Observable<SystemChangePasswordResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface AuthServiceController {
  /** user actions */

  register(request: RegisterRequest, metadata?: Metadata): Observable<RegisterResponse>;

  login(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  verifyOtp(request: VerifyOtpRequest, metadata?: Metadata): Observable<VerifyOtpResponse>;

  logout(request: LogoutRequest, metadata?: Metadata): Observable<LogoutResponse>;

  refresh(request: RefreshRequest, metadata?: Metadata): Observable<RefreshResponse>;

  setTokenVersion(request: SetTokenVersionRequest, metadata?: Metadata): Observable<SetTokenVersionResponse>;

  getTokenVersion(request: GetTokenVersionRequest, metadata?: Metadata): Observable<GetTokenVersionResponse>;

  getBan(request: GetBanRequest, metadata?: Metadata): Observable<GetBanResponse>;

  changePassword(request: ChangePasswordRequest, metadata?: Metadata): Observable<ChangePasswordResponse>;

  resetPassword(request: ResetPasswordRequest, metadata?: Metadata): Observable<ResetPasswordResponse>;

  requestResetPassword(
    request: RequestResetPasswordRequest,
    metadata?: Metadata,
  ): Observable<RequestResetPasswordResponse>;

  changeEmail(request: ChangeEmailRequest, metadata?: Metadata): Observable<ChangeEmailResponse>;

  changeRolePartner(request: ChangeRolePartnerRequest, metadata?: Metadata): Observable<ChangeRolePartnerResponse>;

  getEmailUser(request: GetEmailUserRequest, metadata?: Metadata): Observable<GetEmailUserResponse>;

  getEmailUserByUsername(
    request: GetEmailUserByUsernameRequest,
    metadata?: Metadata,
  ): Observable<GetEmailUserByUsernameResponse>;

  getProfile(request: GetProfileRequest, metadata?: Metadata): Observable<GetProfileReponse>;

  changeAvatar(request: ChangeAvatarRequest, metadata?: Metadata): Observable<ChangeAvatarResponse>;

  getRealnameAvatar(request: GetRealnameAvatarRequest, metadata?: Metadata): Observable<GetRealnameAvatarResponse>;

  getAllUser(request: GetAllUserRequest, metadata?: Metadata): Observable<GetAllUserResponse>;

  /** admin actions */

  changeRole(request: ChangeRoleRequest, metadata?: Metadata): Observable<ChangeRoleResponse>;

  banUser(request: BanUserRequest, metadata?: Metadata): Observable<BanUserResponse>;

  unbanUser(request: UnbanUserRequest, metadata?: Metadata): Observable<UnbanUserResponse>;

  sendEmailToUser(request: SendEmailToUserRequest, metadata?: Metadata): Observable<SendemailToUserResponse>;

  /** admin service gọi khi check account có đủ điều kiện đăng bán không */

  checkAccount(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  /** Login google */

  loginWithGoogle(request: LoginWithGoogleRequest, metadata?: Metadata): Observable<LoginWithGoogleResponse>;

  /** System (api cho hệ thống) */

  systemChangePassword(
    request: SystemChangePasswordRequest,
    metadata?: Metadata,
  ): Observable<SystemChangePasswordResponse>;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "register",
      "login",
      "verifyOtp",
      "logout",
      "refresh",
      "setTokenVersion",
      "getTokenVersion",
      "getBan",
      "changePassword",
      "resetPassword",
      "requestResetPassword",
      "changeEmail",
      "changeRolePartner",
      "getEmailUser",
      "getEmailUserByUsername",
      "getProfile",
      "changeAvatar",
      "getRealnameAvatar",
      "getAllUser",
      "changeRole",
      "banUser",
      "unbanUser",
      "sendEmailToUser",
      "checkAccount",
      "loginWithGoogle",
      "systemChangePassword",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
